mojor updates for BeagleBone build

diff --git a/ttylinux-build/Makefile b/ttylinux-build/Makefile
--- a/ttylinux-build/Makefile
+++ b/ttylinux-build/Makefile
@@ -320,6 +320,7 @@ clean:	scripts/bld-clean.sh
 	fi;								\
 	(scripts/bld-clean.sh all);					\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-clean-1.sh ]; then			\
 			(site/bld-clean-1.sh all);			\
@@ -350,6 +351,7 @@ kclean:	scripts/bld-clean.sh
 	fi;								\
 	(scripts/bld-clean.sh kernel);					\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-clean-1.sh ]; then			\
 			(site/bld-clean-1.sh kernel);			\
@@ -378,6 +380,7 @@ pclean:	scripts/bld-clean.sh
 	fi;								\
 	(scripts/bld-clean.sh packages);				\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-clean-1.sh ]; then			\
 			(site/bld-clean-1.sh packages);			\
@@ -407,6 +410,7 @@ init:	scripts/bld-init.sh
 	fi;								\
 	(scripts/bld-init.sh);						\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-init-1.sh ]; then			\
 			(site/bld-init-1.sh);				\
@@ -429,6 +433,7 @@ pkgs:	ttylinux-pkglst.txt var/run/init is_build_coherent scripts/bld-packages.sh
 	fi;								\
 	(scripts/bld-packages.sh);					\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-packages-1.sh ]; then			\
 			(site/bld-packages-1.sh);			\
@@ -451,6 +456,7 @@ pkgs_:	ttylinux-pkglst.txt var/run/init is_build_coherent scripts/bld-packages.s
 	fi;								\
 	(scripts/bld-packages.sh continue);				\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-packages-1.sh ]; then			\
 			(site/bld-packages-1.sh);			\
@@ -473,6 +479,7 @@ kernel:	scripts/bld-kernel.sh
 	fi;								\
 	(scripts/bld-kernel.sh);					\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-kernel-1.sh ]; then			\
 			(site/bld-kernel-1.sh);				\
@@ -495,6 +502,7 @@ fsys:	var/run/packages is_build_coherent scripts/bld-fsys.sh
 	fi;								\
 	(scripts/bld-fsys.sh);						\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-fsys-1.sh ]; then			\
 			(site/bld-fsys-1.sh);				\
@@ -517,6 +525,7 @@ distdir:	var/run/fsys var/run/kernel scripts/bld-distdir.sh
 	fi;								\
 	(scripts/bld-distdir.sh);					\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-distdir-1.sh ]; then			\
 			(site/bld-distdir-1.sh);			\
@@ -539,6 +548,7 @@ distimg:	var/run/distdir scripts/bld-distimg.sh
 	fi;								\
 	(scripts/bld-distimg.sh);					\
 	mystat=$$?;							\
+	[ $$mystat -eq 0 ] || echo "ERROR";				\
 	if [ x"$${TTYLINUX_SITE_SCRIPTS:-}" = x"y" ]; then		\
 		if [ -x site/bld-distimg-1.sh ]; then			\
 			(site/bld-distimg-1.sh);			\
